#!/usr/bin/env node

if (!require('assert').strict) {
	console.error("We require Node.js version 10 or later; you're using " + process.version);
	process.exit(1);
}

var execSync = require('child_process').execSync;
var fs = require('fs');
var path = require('path');

process.chdir(__dirname);

var args = process.argv.slice(2);
var localServerOption = args.indexOf('--local-server');
if (localServerOption >= 0) {
	var localServerDir = args[localServerOption + 1];
	if (!localServerDir || localServerDir.startsWith('--')) {
		console.error('Usage: node build full --local-server <server-directory>');
		process.exit(1);
	}
	process.env.PS_SERVER_PATH = path.resolve(__dirname, localServerDir);
	args.splice(localServerOption, 2);
}
if (args.length > 1 || (args[0] && args[0].startsWith('--'))) {
	console.error('Usage: node build [full|indexes|learnsets|minidex] [--local-server <server-directory>]');
	process.exit(1);
}
require('./build-tools/server-source');

try {
	require.resolve('@babel/core');
} catch (e) {
	console.log('Installing dependencies...');
	execSync('npm install', {stdio: 'inherit'});
}

try {
	require.resolve('./config/config');
} catch (err) {
	if (err.code !== 'MODULE_NOT_FOUND') throw err; // should never happen

	console.log('config.js does not exist. Creating one with default settings...');
	fs.writeFileSync(
		'config/config.js',
		fs.readFileSync('config/config-example.js')
	);
}

var options = {cwd: __dirname, stdio: 'inherit'};
var full = '';

switch (args[0] || '') {
case 'full':
	execSync(`node ./build-tools/build-indexes`, options);
	execSync(`node ./build-tools/build-learnsets`, options);
	execSync(`node ./build-tools/build-minidex`, options);
	full = ' full';
	break;
case 'indexes':
	execSync(`node ./build-tools/build-indexes`, options);
	break;
case 'learnsets':
	execSync(`node ./build-tools/build-learnsets`, options);
	break;
case 'minidex':
case 'sprites':
	execSync(`node ./build-tools/build-minidex`, options);
	break;
case 'replays':
	execSync(`node ./build-tools/build-replays`, options);
	process.exit();
	break;
case 'test-only':

	break;
case '':
	break;
default:
	console.log(`Unrecognized command ${args[0]}`);
	process.exit(1);
	break;
}

execSync(`node ./build-tools/update` + full, options);

if (full) {
	try {
		execSync(`node ./build-tools/build-replays`, options);
	} catch (e) {}
}
